### ISSUE TITLE
Qualcomm Vuforia package conflicts

### ISSUE THREAD

**Issue by jonwho** [InvexGames/MaterialUI#3]
Importing the MaterialUI package along with the Vuforia package causes compiler errors.

Sample error:
Assets/MaterialUI/Scripts/CheckboxConfig.cs(49,48): error CS1061: Type `Image' does not contain a definition for `gameObject' and no extension method `gameObject' of type `Image' could be found (are you missing a using directive or an assembly reference?)

**Comment by jonwho** [comment]
The package is here https://developer.vuforia.com/resources/sdk/unity

**Comment by InvexGames** [comment]
Thanks, I'll try to fix that issue in the next release.

**Comment by InvexGames** [comment]
Hey jonwho, it looks like the bug is actually an issue with Vuforia and Unity 4.6 in general, where any reference to 'Image' without 'UnityEngine.UI.' in front of it references the non-namespaced Vuforia image. It looks like they are namespacing it (and fixing the issue) in their 4.0 release.

See more here: https://developer.vuforia.com/forum/issues-and-bugs/qualcomm-vuforia-conflict-unity-46&sort=2

**Comment by jonwho** [comment]
Thanks for clearing that up. Importing Vuforia 4 works!
